[theme]
base="light"

primaryColor = '#FFFFFF00'


backgroundColor = '#FFFFFF00'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f7faff'

# Color used for almost all text
textColor = '#646562'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"